# Generated by Django 5.0.6 on 2024-05-31 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=522)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=522)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='webApp.menucategory')),
            ],
        ),
        migrations.CreateModel(
            name='Menudivison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=522)),
                ('menu', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='menu_divisions', to='webApp.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Menusubdivison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=522)),
                ('menudiv', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='menu_sub_divisions', to='webApp.menudivison')),
            ],
        ),
        migrations.CreateModel(
            name='Menuitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=522)),
                ('description', models.TextField()),
                ('parent_menu', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='webApp.menu')),
                ('subdivision', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='menuitem_day', to='webApp.menusubdivison')),
            ],
        ),
    ]
