# Generated by Django 5.0.6 on 2024-06-27 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_userssuggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuitem_day', to='webApp.menusubdivison'),
        ),
    ]
