# Generated by Django 4.0.6 on 2024-07-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0005_alter_kitchen_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkGroupModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=522, null=True)),
                ('module', models.CharField(max_length=522, null=True)),
            ],
        ),
    ]
