# Generated by Django 4.0.6 on 2024-07-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0006_linkgroupmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=522, null=True)),
            ],
        ),
    ]
