# Generated by Django 5.0.6 on 2024-07-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0007_systemmodules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='subdivision',
            field=models.TextField(blank=True, null=True),
        ),
    ]
