# Generated by Django 5.0.6 on 2024-07-30 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0012_adminaddress_address_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_count',
        ),
        migrations.AddField(
            model_name='menucategory',
            name='menu_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='ads_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='daily_deals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='image',
            field=models.FileField(blank=True, max_length=122, null=True, upload_to='static/items_avatar'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(default='In-process', max_length=222)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_details', models.CharField(max_length=500, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('item', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webApp.menuitems')),
                ('order', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='webApp.orders')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAddson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='adds_on_items', to='webApp.menuitems')),
                ('order', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order_addson', to='webApp.orders')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=122, null=True)),
                ('card_id', models.CharField(max_length=122, null=True)),
                ('ccv', models.IntegerField(null=True)),
                ('exp_month', models.CharField(max_length=122, null=True)),
                ('exp_year', models.CharField(max_length=122, null=True)),
                ('last4', models.CharField(max_length=122, null=True)),
                ('name_on_card', models.CharField(max_length=122, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='PaymentMethod', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webApp.paymentmethods'),
        ),
    ]
