# Generated by Django 5.0.6 on 2024-08-01 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0015_kitchenaddress_address_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchenaddress',
            name='Kitchen',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_address_record', to='webApp.kitchen'),
        ),
    ]
