# Generated by Django 5.0.6 on 2024-08-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0016_alter_kitchenaddress_kitchen'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddson',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
