# Generated by Django 5.0.6 on 2024-08-08 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0018_alter_orders_payment_method_alter_orders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='kitchen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kitchen_Orders', to='webApp.kitchen'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(default='to_be_confirmed', max_length=222),
        ),
    ]
