# Generated by Django 5.0.6 on 2024-08-12 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0019_orders_kitchen_alter_orders_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentaccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban_number', models.CharField(max_length=522, null=True)),
                ('account_title', models.CharField(max_length=522, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_payment_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
