# Generated by Django 5.0.6 on 2024-08-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0020_paymentaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
