# Generated by Django 5.0.6 on 2024-08-13 12:13

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0021_kitchen_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchenmedia',
            name='file',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=None, size=None, upload_to='static/kitchen_media'),
        ),
    ]
