# Generated by Django 5.0.6 on 2024-08-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0022_alter_kitchenmedia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='customer_name',
            field=models.CharField(max_length=522, null=True),
        ),
    ]
