# Generated by Django 5.0.6 on 2024-08-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0023_orders_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_fcm',
            field=models.TextField(null=True),
        ),
    ]
