# Generated by Django 5.0.6 on 2024-08-19 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0025_alter_kitchenspeciality_kitchen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchenmedia',
            name='Kitchen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_media_records', to='webApp.kitchen'),
        ),
    ]
