# Generated by Django 5.0.6 on 2024-08-19 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0026_alter_kitchenmedia_kitchen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='item_ordered', to='webApp.menuitems'),
        ),
    ]
