# Generated by Django 5.0.6 on 2024-08-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0027_alter_orderitems_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address_details',
            field=models.CharField(max_length=522, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
