# Generated by Django 5.0.6 on 2024-08-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0028_orders_address_details_orders_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaccounts',
            name='contact',
            field=models.CharField(max_length=522, null=True),
        ),
    ]
