# Generated by Django 5.0.6 on 2024-08-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0029_paymentaccounts_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodappSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=522, null=True)),
                ('orders_radius', models.PositiveIntegerField(default=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='paymentaccounts',
            name='contact',
        ),
    ]
