# Generated by Django 5.0.6 on 2024-09-02 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0030_foodappsettings_remove_paymentaccounts_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_title', models.CharField(max_length=522, null=True)),
                ('role', models.CharField(max_length=522, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='OrderMenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_details', models.CharField(max_length=500, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('menu', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='menu_ordered', to='webApp.menu')),
                ('order', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order_menu_items', to='webApp.orders')),
            ],
        ),
    ]
