# Generated by Django 5.0.6 on 2024-09-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0031_orderstatus_menu_total_price_ordermenuitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_cod',
            field=models.BooleanField(null=True),
        ),
    ]
