# Generated by Django 5.0.6 on 2024-09-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0033_foodappsettings_terms_and_c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='Kitchen_share_percent',
            field=models.CharField(max_length=522, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='contact',
            field=models.CharField(max_length=522, null=True),
        ),
    ]
