# Generated by Django 5.0.6 on 2024-09-10 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0034_menucategory_kitchen_share_percent_orders_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='kitchenOrdersPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen_share_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(default='pending', max_length=522)),
                ('Kitchen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_payment_info', to='webApp.kitchen')),
                ('order', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order_payment_info', to='webApp.orders')),
            ],
        ),
    ]
