# Generated by Django 5.0.6 on 2024-09-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0035_kitchenorderspayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=522)),
                ('address_details', models.CharField(max_length=522, null=True)),
                ('address_line1', models.CharField(max_length=122, null=True)),
                ('address_line2', models.CharField(max_length=122, null=True)),
                ('city', models.CharField(max_length=122, null=True)),
                ('country', models.CharField(max_length=122, null=True)),
                ('postal_code', models.CharField(max_length=122, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('contact', models.CharField(max_length=522)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
