# Generated by Django 5.0.6 on 2024-09-18 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0036_riderdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_delivery', to='webApp.orders')),
                ('rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider_orders', to='webApp.riderdetails')),
            ],
        ),
    ]
