# Generated by Django 5.0.6 on 2024-09-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0037_riderorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProcessedStatuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.PositiveIntegerField()),
                ('order_id', models.PositiveIntegerField()),
            ],
        ),
    ]
