# Generated by Django 5.0.6 on 2024-09-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0038_orderprocessedstatuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='is_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
