# Generated by Django 5.0.6 on 2024-09-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0039_orderstatus_is_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='ordering_bit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
