# Generated by Django 5.0.6 on 2024-09-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0040_orderstatus_ordering_bit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
