# Generated by Django 5.0.6 on 2024-10-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0041_orderstatus_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderorders',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
