# Generated by Django 5.0.6 on 2024-10-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0042_riderorders_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderdetails',
            name='device_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='riderdetails',
            name='registration_id',
            field=models.TextField(null=True),
        ),
    ]
