# Generated by Django 5.0.6 on 2024-10-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0044_menuitems_exclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='rider_pending',
            field=models.BooleanField(default=False),
        ),
    ]
