# Generated by Django 5.0.6 on 2024-10-29 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0046_orderstatus_is_in_process_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=522)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, max_length=522, null=True, upload_to='static/our_services')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteDynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hero_section_title', models.CharField(max_length=522)),
                ('Hero_section_description', models.TextField()),
                ('Hero_section_image', models.FileField(blank=True, max_length=522, null=True, upload_to='static/website_dynamics')),
                ('about_section_title', models.CharField(max_length=522)),
                ('about_section_description', models.TextField()),
                ('about_section_image', models.FileField(blank=True, max_length=522, null=True, upload_to='static/website_dynamics')),
                ('daily_section_title', models.CharField(max_length=522)),
                ('daily_section_description', models.TextField()),
                ('menus_section_title', models.CharField(max_length=522)),
                ('menus_section_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OurServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=522)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_services', to='webApp.ourservices')),
            ],
        ),
    ]
