# Generated by Django 5.0.6 on 2024-10-29 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0047_ourservices_websitedynamic_ourservicessection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourservicessection',
            name='service',
        ),
        migrations.AddField(
            model_name='ourservices',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_services', to='webApp.ourservicessection'),
        ),
    ]
