# Generated by Django 5.0.6 on 2024-10-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0048_remove_ourservicessection_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='subscription_info',
            field=models.JSONField(null=True),
        ),
    ]
