# Generated by Django 5.0.6 on 2024-11-04 06:45

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0049_orders_subscription_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=522)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='kitchenorderspayment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kitchenorderspayment',
            name='is_payable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='extra_notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='to_be_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='its_color_code',
            field=models.CharField(max_length=522, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(default='pending', max_length=222),
        ),
        migrations.CreateModel(
            name='OurClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=522)),
                ('review', models.TextField()),
                ('avatar', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=None, size=None, upload_to='static/clients_avatar')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_clients', to='webApp.clients')),
            ],
        ),
        migrations.CreateModel(
            name='RiderDeliveryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_share_amount', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(default='pending', max_length=522)),
                ('is_payable', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('order', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order_delivery_info', to='webApp.orders')),
                ('rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider_delivery_payment', to='webApp.kitchen')),
            ],
        ),
        migrations.CreateModel(
            name='RiderPaymentaccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban_number', models.CharField(max_length=522, null=True)),
                ('account_title', models.CharField(max_length=522, null=True)),
                ('bank_name', models.CharField(max_length=522, null=True)),
                ('rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider_payment_accounts', to='webApp.riderdetails')),
            ],
        ),
    ]
