# Generated by Django 5.0.6 on 2024-11-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0050_clients_kitchenorderspayment_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
