# Generated by Django 5.0.6 on 2024-11-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0051_orders_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_details',
            field=models.TextField(null=True),
        ),
    ]
