# Generated by Django 5.0.6 on 2024-11-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0053_orders_has_menu_orders_is_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprocessedstatuses',
            name='processed_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
