# Generated by Django 5.0.6 on 2024-11-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0055_ridercomissionsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='last_date_to_deliver',
            field=models.DateField(null=True),
        ),
    ]
