# Generated by Django 5.0.6 on 2024-11-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0056_orders_last_date_to_deliver'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='delivery_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
