# Generated by Django 5.0.6 on 2024-11-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0058_orders_kitchen_to_customer_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='its_color_code',
            field=models.CharField(max_length=522, null=True),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='is_cod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
