# Generated by Django 5.0.6 on 2024-11-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0059_orders_its_color_code_orderstatus_is_cod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menufoodrecords',
            name='is_cooked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menufoodrecords',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='is_cooked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
