# Generated by Django 4.2.16 on 2024-11-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0060_menufoodrecords_is_cooked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
