# Generated by Django 5.0.6 on 2024-11-18 08:40

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0061_newsletterrecords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=522)),
                ('file', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=None, size=None, upload_to='static/Deals_avatars')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='dicounted_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='dicounted_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='deal',
            field=models.ManyToManyField(related_name='deal_items', to='webApp.deals'),
        ),
    ]
