# Generated by Django 5.0.6 on 2024-11-19 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0063_deals_description_deals_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDealItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_details', models.CharField(max_length=500, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deal', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='deal_ordered', to='webApp.deals')),
                ('order', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order_deal_items', to='webApp.orders')),
            ],
        ),
    ]
