# Generated by Django 5.0.6 on 2024-11-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0064_orderdealitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdealitems',
            name='order_date',
        ),
        migrations.AddField(
            model_name='orderdealitems',
            name='delivery_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
