# Generated by Django 5.0.6 on 2024-11-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0066_dealsaddson_itemsaddson_menusaddson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alladdson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=522)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, max_length=122, null=True, upload_to='static/all_addson')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('dicounted_price', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('deal', models.ManyToManyField(related_name='deal_addson_records', to='webApp.deals')),
                ('item', models.ManyToManyField(related_name='item_addson_records', to='webApp.deals')),
                ('menu', models.ManyToManyField(related_name='menu_addson_records', to='webApp.deals')),
            ],
        ),
    ]
