# Generated by Django 5.0.6 on 2024-11-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0067_alladdson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alladdson',
            name='item',
            field=models.ManyToManyField(related_name='item_addson_records', to='webApp.menuitems'),
        ),
        migrations.AlterField(
            model_name='alladdson',
            name='menu',
            field=models.ManyToManyField(related_name='menu_addson_records', to='webApp.menu'),
        ),
    ]
