# Generated by Django 5.0.6 on 2024-11-22 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0068_alter_alladdson_item_alter_alladdson_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsaddson',
            name='item',
        ),
        migrations.RemoveField(
            model_name='menusaddson',
            name='menu',
        ),
        migrations.CreateModel(
            name='Dealsorderaddson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealorder_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealorder_addson_records', to='webApp.orderdealitems')),
                ('orderdeal_addson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_dealorder_addson', to='webApp.alladdson')),
            ],
        ),
        migrations.CreateModel(
            name='Itemsorderaddson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitems_addson_records', to='webApp.orderitems')),
                ('orderitems_addson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_itemorder_addson', to='webApp.alladdson')),
            ],
        ),
        migrations.CreateModel(
            name='Menuorderaddson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuorder_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuorder_addson_records', to='webApp.ordermenuitems')),
                ('ordermenu_addson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_menuorder_addson', to='webApp.alladdson')),
            ],
        ),
        migrations.DeleteModel(
            name='Dealsaddson',
        ),
        migrations.DeleteModel(
            name='Itemsaddson',
        ),
        migrations.DeleteModel(
            name='Menusaddson',
        ),
    ]
