# Generated by Django 5.0.6 on 2024-11-22 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0069_remove_itemsaddson_item_remove_menusaddson_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderdeliverypayment',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rider_delivery_payment', to='webApp.riderdetails'),
        ),
    ]
