# Generated by Django 5.0.6 on 2024-11-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0070_alter_riderdeliverypayment_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealsorderaddson',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='itemsorderaddson',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='menuorderaddson',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
