# Generated by Django 5.0.6 on 2024-12-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0071_dealsorderaddson_quantity_itemsorderaddson_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdealitems',
            name='is_cooked',
            field=models.BooleanField(default=False),
        ),
    ]
