# Generated by Django 5.0.6 on 2024-12-18 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0072_orderdealitems_is_cooked'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodappsettings',
            name='Kitchen_share_percent',
            field=models.PositiveIntegerField(default=90, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
