# Generated by Django 5.0.6 on 2024-12-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0074_riderorders_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderdeliverypayment',
            name='delivery_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
