# Generated by Django 5.0.6 on 2024-12-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0075_riderdeliverypayment_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenorderspayment',
            name='delivery_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
